import { priceRarity } from './case-mechanics';
export type DrinkCategory = 'coffee' | 'tea' | 'milktea' | 'juice' | 'smoothie' | 'soda' | 'other';
export type Drink={customId?:string;name:string;sub:string;price:number;rarity:number;image:number;category:DrinkCategory;decaf?:boolean;quip:string};
// Approximate afternoon drink prices in thousands of VND, not shop quotes.
const raw:Omit<Drink,'rarity'>[]=[
  {"name":"Trà đá","sub":"Vỉa hè • Việt Nam","price":5,"image":0,"category":"tea","quip":"Rẻ nhất bảng giá. Mát nhất tâm hồn."},
  {"name":"Nước mía","sub":"Ép tươi • Việt Nam","price":15,"image":1,"category":"other","decaf":true,"quip":"Ngọt như lời hứa deadline hôm nay xong sớm."},
  {"name":"Trà chanh","sub":"Vỉa hè • Việt Nam","price":15,"image":2,"category":"tea","quip":"Một cốc trà chanh, cả hội đồng chốt đơn."},
  {"name":"Cà phê đen đá","sub":"Cà phê • Việt Nam","price":18,"image":3,"category":"coffee","quip":"Đắng thật nhưng tỉnh thật."},
  {"name":"Cà phê sữa đá","sub":"Cà phê • Việt Nam","price":20,"image":4,"category":"coffee","quip":"Combo quốc dân, không bao giờ lỗi mốt."},
  {"name":"Trà tắc","sub":"Quất mật ong • Việt Nam","price":18,"image":5,"category":"tea","decaf":true,"quip":"Chua chua ngọt ngọt như deadline hôm nay."},
  {"name":"Trà đào cam sả","sub":"Trà trái cây • Việt Nam","price":35,"image":6,"category":"tea","quip":"Ping vào nhóm chat là có đứa rủ đi mua."},
  {"name":"Sữa chua đá","sub":"Lên men • Việt Nam","price":20,"image":7,"category":"other","decaf":true,"quip":"Vừa uống vừa tự nhủ hôm nay ăn healthy."},
  {"name":"Sữa đậu nành","sub":"Nóng/đá • Việt Nam","price":12,"image":8,"category":"other","decaf":true,"quip":"Giản dị nhưng chưa bao giờ bị chê."},
  {"name":"Nước dừa","sub":"Dừa tươi • Việt Nam","price":25,"image":9,"category":"other","decaf":true,"quip":"Điện giải tự nhiên cho ca chiều dài hơi."},
  {"name":"Bạc xỉu","sub":"Cà phê sữa • Việt Nam","price":22,"image":10,"category":"coffee","quip":"Cho người sợ đắng nhưng vẫn cần tỉnh."},
  {"name":"Trà gừng mật ong","sub":"Trà nóng • Việt Nam","price":20,"image":11,"category":"tea","decaf":true,"quip":"Ấm bụng, ấm cả buổi họp muộn."},
  {"name":"Chè khúc bạch","sub":"Tráng miệng lạnh • Việt Nam","price":30,"image":12,"category":"other","decaf":true,"quip":"Uống hay ăn cũng chill như nhau."},
  {"name":"Cà phê cốt dừa","sub":"Cà phê • Việt Nam","price":29,"image":13,"category":"coffee","quip":"Vị lạ, ghiền nhanh, ví nhẹ."},
  {"name":"Trà sữa trân châu đường đen","sub":"Trà sữa • Đài Loan","price":45,"image":14,"category":"milktea","quip":"Rare drop cuối tuần, giá không hề rẻ."},
  {"name":"Trà sữa truyền thống","sub":"Trà sữa • Đài Loan","price":35,"image":15,"category":"milktea","quip":"Món quốc dân của mọi tủ lạnh văn phòng."},
  {"name":"Hồng trà sữa kem cheese","sub":"Trà sữa • Đài Loan","price":42,"image":16,"category":"milktea","quip":"Lớp cheese phủ lên là auto tăng độ ngon."},
  {"name":"Trà sữa matcha","sub":"Trà sữa • Nhật Bản","price":40,"image":17,"category":"milktea","quip":"Xanh mát như deadline vẫn còn xa."},
  {"name":"Trà sữa khoai môn","sub":"Trà sữa • Đài Loan","price":38,"image":18,"category":"milktea","quip":"Tím lịm tim, ngọt lịm bụng."},
  {"name":"Trà ô long sữa","sub":"Trà sữa • Đài Loan","price":32,"image":19,"category":"milktea","quip":"Đắng nhẹ, thanh nhẹ, hợp gu người lớn."},
  {"name":"Trà vải","sub":"Trà trái cây • Việt Nam","price":32,"image":20,"category":"tea","quip":"Ngọt thơm như tin nhắn được duyệt chi."},
  {"name":"Trà ổi hồng","sub":"Trà trái cây • Việt Nam","price":32,"image":21,"category":"tea","quip":"Màu hồng cứu cả buổi chiều xám xịt."},
  {"name":"Trà atiso","sub":"Thảo mộc • Việt Nam","price":25,"image":22,"category":"tea","decaf":true,"quip":"Mát gan, tỉnh táo mà không cần caffeine."},
  {"name":"Nước ép cam","sub":"Ép tươi • Việt Nam","price":25,"image":23,"category":"juice","decaf":true,"quip":"Vitamin C chống chọi deadline hiệu quả."},
  {"name":"Nước ép dưa hấu","sub":"Ép tươi • Việt Nam","price":22,"image":24,"category":"juice","decaf":true,"quip":"Giải nhiệt tức thì, không cần suy nghĩ nhiều."},
  {"name":"Nước ép cà rốt","sub":"Ép tươi • Việt Nam","price":22,"image":25,"category":"juice","decaf":true,"quip":"Đẹp da hay không chưa rõ, nhưng ngon là chắc."},
  {"name":"Nước ép táo","sub":"Ép tươi • Việt Nam","price":25,"image":26,"category":"juice","decaf":true,"quip":"An toàn mọi khẩu vị, không ai nỡ chê."},
  {"name":"Nước ép dứa","sub":"Ép tươi • Việt Nam","price":22,"image":27,"category":"juice","decaf":true,"quip":"Chua ngọt tỉnh người giữa buổi chiều."},
  {"name":"Nước chanh dây","sub":"Ép tươi • Việt Nam","price":22,"image":28,"category":"juice","decaf":true,"quip":"Chua muốn xỉu nhưng tỉnh táo cực kỳ."},
  {"name":"Sinh tố bơ","sub":"Sinh tố • Việt Nam","price":30,"image":29,"category":"smoothie","decaf":true,"quip":"Béo ngậy như lương thưởng cuối năm."},
  {"name":"Sinh tố xoài","sub":"Sinh tố • Việt Nam","price":28,"image":30,"category":"smoothie","decaf":true,"quip":"Vàng ươm, ngọt lịm, ai cũng gọi thêm ly nữa."},
  {"name":"Sinh tố dâu","sub":"Sinh tố • Việt Nam","price":30,"image":31,"category":"smoothie","decaf":true,"quip":"Hồng hồng dễ thương, ngọt xỉu cả văn phòng."},
  {"name":"Sinh tố việt quất","sub":"Sinh tố • Việt Nam","price":38,"image":32,"category":"smoothie","decaf":true,"quip":"Tím sang, giá cũng sang không kém."},
  {"name":"Sinh tố dừa","sub":"Sinh tố • Việt Nam","price":28,"image":33,"category":"smoothie","decaf":true,"quip":"Béo thơm mùi dừa, quên luôn cả nắng nóng."},
  {"name":"Cà phê muối","sub":"Cà phê • Huế","price":25,"image":34,"category":"coffee","quip":"Nghe lạ nhưng uống một lần là ghiền."},
  {"name":"Cà phê trứng","sub":"Cà phê • Hà Nội","price":30,"image":35,"category":"coffee","quip":"Béo như bánh, tỉnh như cà phê, đúng chuẩn Hà Nội."},
  {"name":"Cold brew","sub":"Cà phê ủ lạnh • Quốc tế","price":40,"image":36,"category":"coffee","quip":"Ủ 12 tiếng cho một buổi chiều không buồn ngủ."},
  {"name":"Espresso","sub":"Cà phê • Ý","price":30,"image":37,"category":"coffee","quip":"Một hớp, tỉnh như vừa nghe sếp gọi tên."},
  {"name":"Americano đá","sub":"Cà phê • Quốc tế","price":32,"image":38,"category":"coffee","quip":"Nhẹ nhàng nhưng đủ đô cho ca chiều dài."},
  {"name":"Cappuccino","sub":"Cà phê • Ý","price":42,"image":39,"category":"coffee","quip":"Lớp bọt sữa đẹp như slide thuyết trình vừa được duyệt."},
  {"name":"Latte","sub":"Cà phê • Ý","price":45,"image":40,"category":"coffee","quip":"Mềm mịn, dễ chiều, hợp mọi tâm trạng."},
  {"name":"Matcha latte","sub":"Trà xanh • Nhật Bản","price":45,"image":41,"category":"milktea","quip":"Xanh mướt như KPI vừa đạt được."},
  {"name":"Trà xanh đá xay","sub":"Đá xay • Nhật Bản","price":48,"image":42,"category":"smoothie","quip":"Lạnh, xay nhuyễn, cứu cả buổi chiều nóng nực."},
  {"name":"Cà phê đá xay","sub":"Đá xay • Quốc tế","price":50,"image":43,"category":"smoothie","quip":"Vừa là cà phê vừa là món tráng miệng."},
  {"name":"Chocolate đá xay","sub":"Đá xay • Quốc tế","price":48,"image":44,"category":"smoothie","quip":"Ngọt liều nhưng đúng lúc cần an ủi."},
  {"name":"Soda chanh dây","sub":"Soda trái cây • Việt Nam","price":30,"image":45,"category":"soda","decaf":true,"quip":"Sủi tanh tách như tin nhắn báo hết giờ họp."},
  {"name":"Soda việt quất","sub":"Soda trái cây • Việt Nam","price":35,"image":46,"category":"soda","decaf":true,"quip":"Xanh tím lịm, ai chụp ảnh cũng phải khoe."},
  {"name":"Soda dâu","sub":"Soda trái cây • Việt Nam","price":32,"image":47,"category":"soda","decaf":true,"quip":"Ngọt nhẹ, ga vừa, vui cả buổi chiều."},
  {"name":"Trà tắc soda","sub":"Soda • Việt Nam","price":28,"image":48,"category":"soda","decaf":true,"quip":"Bản nâng cấp có ga của trà tắc quen thuộc."},
  {"name":"Cacao đá","sub":"Sô cô la • Việt Nam","price":28,"image":49,"category":"other","decaf":true,"quip":"Ngọt ngào xoa dịu một buổi chiều dài."},
  {"name":"Trà bí đao","sub":"Thảo mộc đóng chai • Việt Nam","price":10,"image":50,"category":"tea","decaf":true,"quip":"Mát gan, rẻ ví, ai cũng nên thử."},
  {"name":"Nước sâm","sub":"Thảo mộc • Việt Nam","price":15,"image":51,"category":"other","decaf":true,"quip":"Thanh mát kiểu bà ngoại vẫn hay pha."},
  {"name":"Yakult đá xay","sub":"Lên men • Nhật Bản","price":35,"image":52,"category":"smoothie","decaf":true,"quip":"Chua chua ngọt ngọt, tuổi thơ ai cũng mê."},
  {"name":"Trà sữa Oreo","sub":"Trà sữa • Đài Loan","price":42,"image":53,"category":"milktea","quip":"Bánh quy giòn tan trong từng ngụm."},
  {"name":"Chanh muối","sub":"Giải khát • Việt Nam","price":18,"image":54,"category":"juice","decaf":true,"quip":"Mặn ngọt chua cay đủ vị như một ngày làm việc."},
  {"name":"Cà phê dừa","sub":"Cà phê • Việt Nam","price":32,"image":55,"category":"coffee","quip":"Béo thơm hai lớp, tỉnh táo gấp đôi."},
];
export const drinks:Drink[]=raw.map(drink=>({...drink,rarity:priceRarity(drink.price)}));
